version: "3.8"

services:

  gateway:
    build:
      context: ./gateway
      target: "development"
    ports:
      - "4000:4000"
    container_name: "gateway"
    depends_on: [samplebook, sampleuser]
    labels:
      kompose.service.type: LoadBalancer
  
  sampleuser:
    build:
      context: ./sample-user
      target: "development"
    ports:
      - "3000:3000"
    container_name: "sampleuser"
    depends_on: [rabbitmq]
  
  samplebook:
    build:
      context: ./sample-book
      target: "development"
    ports:
      - "3001:3001"
    container_name: "samplebook"
    depends_on: [rabbitmq]

  rabbitmq:
    image: rabbitmq
    ports:
    - "5672:5672"
    